# Generated by Django 5.1.5 on 2025-02-12 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pavilhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('numero_salas', models.IntegerField(verbose_name='Numero de salas')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('topico_mqtt', models.CharField(editable=False, max_length=100)),
                ('pavilhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.pavilhao')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_da_semana', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=100)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('pavilhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.pavilhao')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sala')),
            ],
        ),
        migrations.CreateModel(
            name='ArCondicionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('potencia_kw', models.FloatField(max_length=20, verbose_name='Potência')),
                ('consumo', models.FloatField(max_length=20, verbose_name='Consumo')),
                ('consumo_unidade', models.CharField(choices=[('kWh/mês', 'kWh/mês'), ('kWh/ano', 'kWh/ano')], default='kWh/ano', max_length=10)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sala')),
            ],
        ),
    ]
