# Generated by Django 5.1.3 on 2025-02-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='turno',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
