# Generated by Django 5.1.5 on 2025-02-11 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArCondicionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('topico_mqtt', models.CharField(max_length=50, verbose_name='Tópico MQTT')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sala')),
            ],
        ),
    ]
