# Generated by Django 5.1.5 on 2025-02-11 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_arcondicionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcondicionado',
            name='topico_mqtt',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+$', 'O tópico MQTT deve conter apenas letras minúsculas e números, sem espaços e sem caracteres especiais.')], verbose_name='Tópico MQTT'),
        ),
    ]
