# Generated by Django 5.1.3 on 2025-02-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_arcondicionado_consumo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_kWh', models.FloatField(verbose_name='Valor em kWh')),
            ],
        ),
    ]
