# Generated by Django 5.1.5 on 2025-02-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_arcondicionado_topico_mqtt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='topico_mqtt',
            field=models.CharField(default='sem_topico', editable=False, max_length=100),
        ),
    ]
