# Generated by Django 5.1.5 on 2025-02-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_sala_topico_mqtt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arcondicionado',
            name='topico_mqtt',
        ),
        migrations.AddField(
            model_name='arcondicionado',
            name='potencia',
            field=models.IntegerField(default=0, verbose_name='Potência'),
        ),
    ]
