# Generated by Django 5.1.3 on 2025-02-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_arcondicionado_topico_mqtt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcondicionado',
            name='potencia',
            field=models.IntegerField(verbose_name='Potência'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='topico_mqtt',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
