# Generated by Django 5.1.5 on 2025-04-14 02:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_grafico_valor_kwh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pavilhao',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AddConstraint(
            model_name='pavilhao',
            constraint=models.UniqueConstraint(fields=('usuario', 'nome'), name='unique_pavilhao_por_usuario'),
        ),
    ]
