# Generated by Django 5.1.5 on 2025-05-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_sala_unique_sala_por_pavilhao_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sala',
            name='unique_sala_por_pavilhao',
        ),
        migrations.AddConstraint(
            model_name='sala',
            constraint=models.UniqueConstraint(fields=('pavilhao', 'nome'), name='unique_sala_por_pavilhao'),
        ),
    ]
