# Generated by Django 5.1.5 on 2025-05-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_sala_unique_sala_por_pavilhao_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sala',
            name='unique_sala_por_pavilhao',
        ),
    ]
